scons -j 3 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=1 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=mpicxx.mpich FC=mpifort CXX=mpicxx.mpich OPT=1 TIMING=1 CPPFLAGS=-fdiagnostics-color=always TEST_THREAD_COUNT=2 USE_HYBRID_OPENMP=1  #TEST_PROCESS_COUNT=4 #DEBUG_OUTPUT=1 

