#!/bin/bash
#Debug
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=/opt/mpich/bin/mpicc FC=mpifort.mpich CXX=/opt/mpich/bin/mpic++ OPT=1 TIMING=0 UNIFORMDECOMPOSITION=1 #DEBUG_OUTPUT=1 CPPFLAGS=-g
scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=/opt/mpich/bin/mpicc FC= CXX=/opt/mpich/bin/mpic++ OPT=1 TIMING=0 UNIFORMDECOMPOSITION=1 DEBUG_OUTPUT=0 CPPFLAGS=-g

#Release
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=1 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=/opt/mpich/bin/mpicc FC=mpifort.mpich CXX=/opt/mpich/bin/mpic++ OPT=1 TIMING=0

#Helium
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=mpicc.mpich FC=mpifort.mpich CXX=mpicxx.mpich OPT=1 TIMING=0 UNIFORMDECOMPOSITION=1 #DEBUG_OUTPUT=1

#HLRS
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=cc FC= CXX=CC OPT=1 TIMING=0 UNIFORMDECOMPOSITION=1 #DEBUG_OUTPUT=1

#LRZ
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=mpicc FC=mpifort.mpich CXX=mpiCC OPT=1 TIMING=0 UNIFORMDECOMPOSITION=1 #DEBUG_OUTPUT=1
