#!/bin/bash
#Debug
scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=/opt/mpich/bin/mpicc FC=mpifort.mpich CXX=/opt/mpich/bin/mpic++ OPT=1 TIMING=0 #DEBUG_OUTPUT=1
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=/opt/mpich/bin/mpicc FC=mpifort.mpich CXX=/opt/mpich/bin/mpic++ OPT=1 TIMING=0 DEBUG_OUTPUT=1 &> compile.out

#Release
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=1 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=/opt/mpich/bin/mpicc FC=mpifort.mpich CXX=/opt/mpich/bin/mpic++ OPT=1 TIMING=0

#Helium
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=mpicc.mpich FC=mpifort.mpich CXX=mpicxx.mpich OPT=1 TIMING=0 #DEBUG_OUTPUT=1


#HLRS
#scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=cc FC=mpifort.mpich CXX=CC OPT=1 TIMING=0 #DEBUG_OUTPUT=1


