#!/bin/bash
#script to visualize GENE neoclass data with gnuplot
#usage: gplot <neoclassfile> -n <neoclass column> -f 
TIMESTAMP=$(date +%m%d%y%H%M%S)
tmppltfile="/tmp/gplot.$USER.$TIMESTAMP.plt"
tmpdatfile="/tmp/gplot.$USER.$TIMESTAMP.dat"
tmpfitfile="/tmp/gplot.$USER.$TIMESTAMP.fit"
neoclass_col=2
first=0
validfiles=''
fit_start=-1
fit_end=1E9
mean_start=-1
mean_end=1E9
epsfile=''
xrsc=1.0
yrsc=1.0
tmax=''
tmin=''

until [ -z "$1" ]; do
    if [[ $1 == *"neoclass"* ]] && [ -f $1 ]
    then
	validfiles="$validfiles $1"
	n_spec=`awk '{if (NF==1) {n_spec=0} else {n_spec+=1; print n_spec}}' $1 | tail -1`
    elif [ "$1" == "-n" ]; then
	shift
	neoclass_col=$1
    elif [ "$1" == "-f" ]; then
	shift
	fit_start=$1
    elif [ "$1" == "-fe" ]; then
	shift
	fit_end=$1
    elif [ "$1" == "-m" ]; then
	shift
	mean_start=$1
    elif [ "$1" == "-me" ]; then
	shift
	mean_end=$1
    elif [ "$1" == "-eps" ]; then
	shift
	epsfile=$1
    elif [ "$1" == "-xrsc" ];then
	shift
	xrsc=$1
    elif [ "$1" == "-yrsc" ];then
	shift
	yrsc=$1
    elif [ "$1" == "-tmax" ];then
	shift
	tmax=$1
    elif [ "$1" == "-tmin" ];then
	shift
	tmin=$1
    else
	echo "usage: gplot <neoclass files>
       optional arguments:
        -n <neoclass column>
        -f <exp. fit time start>
        -m <mean fit time start>
	-eps (for EPS output)
	-tmax <maximum plotting time>
	-tmin <minimum plotting time>
	-xrsc <rescale factor x axis>
	-yrsc <rescale factor y axis>"
	exit
    fi
    shift
done

if [ "$validfiles" != "" ]; then
    echo "reading and transforming neoclass data ..."

    cat $validfiles | awk 'BEGIN {lasttime=-1} {if (NF==1) {time=$1; if (time<lasttime) {print "\n\n"}; lasttime=time} else print time,$0};' > $tmpdatfile

    Nruns=`grep -c '^$' $tmpdatfile`
    Nruns=`expr $Nruns / 3 + 1`

    case "$neoclass_col" in
	'1')
	ylabel='t'
	;;
	'2')
	ylabel='<G_neo>'
	;;
	'3')
	ylabel='<Q_neo>'
	;;
	'4')
	ylabel='<P_neo>'
	;;
	'5')
	ylabel='<j_b>'
	;;
	esac

###################### create plt file #############################

    echo "#temporary file created by gplot
    set xzeroaxis lt -1
    set xlabel 't' 
    set ylabel '$ylabel'
    set xrange [$tmin:$tmax]
    set fit logfile '$tmpfitfile'" > $tmppltfile
# 't / [v_t,ref/L_perp]' 
# 'Q_es / [p0 v_t,ref rho_ref^2 / L_perp^2]'
    irun=0
    cur_spec=0
    lc=0

    while [ $irun -lt $Nruns ]; do
	cur_spec=0
	while [ $cur_spec -lt $n_spec ]; do
	    if [[ $irun -eq 0 && $cur_spec -eq 0 ]]; then
		echo "plot '$tmpdatfile' i $irun ev $n_spec::$cur_spec u ("\$"1*$xrsc):("\$"$neoclass_col*$yrsc) tit 'run $irun, species $cur_spec' w lp lt $lc lw 3" >> $tmppltfile
	    else
		echo "replot '$tmpdatfile' i $irun ev $n_spec::$cur_spec u ("\$"1*$xrsc):("\$"$neoclass_col*$yrsc) tit 'run $irun, species $cur_spec' w lp lt $lc lw 3" >> $tmppltfile
	    fi
	    cur_spec=`expr $cur_spec + 1`
	    lc=`expr $lc + 1`
	done
	irun=`expr $irun + 1`
    done

##################### exponential fit ###############################
    if [ $fit_start -ge 0 ]; then
	irun=0
	cur_spec=0
	lc=0
	
	while [ $irun -lt $Nruns ]; do
	    cur_spec=0
	    while [ $cur_spec -lt $n_spec ]; do
		echo "f$lc(x)=a$lc*x+b$lc
            fit f$lc(x) '' i $irun ev $n_spec::$cur_spec u (("\$"1>$fit_start&&"\$"1<$fit_end)?"\$"1*$xrsc:1/0):(log("\$"$neoclass_col*$yrsc)) via a$lc,b$lc" >> $tmppltfile
		cur_spec=`expr $cur_spec + 1`
		lc=`expr $lc + 1`
	    done
	    irun=`expr $irun + 1`
	done	    

	irun=0
	cur_spec=0
	lc=0
	echo "print '========================================='" >> $tmppltfile
	while [ $irun -lt $Nruns ]; do
	    cur_spec=0
	    while [ $cur_spec -lt $n_spec ]; do
		echo "replo exp(f$lc(x)) w l lt $lc lw 1
            print 'run $irun, spec $cur_spec: gamma($ylabel)=',gprintf(\"%g\",a$lc),'  ( :2=',gprintf(\"%g\",a$lc*0.5),' )'" >> $tmppltfile
		cur_spec=`expr $cur_spec + 1`
		lc=`expr $lc + 1`
	    done
	    irun=`expr $irun + 1`
	done	    
	    
	echo "print '========================================='" >> $tmppltfile
    fi

##################### mean value fit ###############################

    if [ $mean_start -ge 0 ]; then
	irun=0
	cur_spec=0
	lc=0
	
	while [ $irun -lt $Nruns ]; do
	    cur_spec=0
	    while [ $cur_spec -lt $n_spec ]; do
		echo "mm$lc(x)=m$lc
            fit mm$lc(x) '' i $irun ev $n_spec::$cur_spec u (("\$"1>$mean_start&&"\$"1<$mean_end)?"\$"1*$xrsc:1/0):("\$"$neoclass_col*$yrsc) via m$lc
            stddev$lc = sqrt(FIT_WSSR / (FIT_NDF + 1 ))" >> $tmppltfile
		cur_spec=`expr $cur_spec + 1`
		lc=`expr $lc + 1`
	    done
	    irun=`expr $irun + 1`
	done	    

	irun=0
	cur_spec=0
	lc=0
	echo "print '========================================='" >> $tmppltfile
	while [ $irun -lt $Nruns ]; do
	    cur_spec=0
	    while [ $cur_spec -lt $n_spec ]; do
		echo "replo mm$lc(x) w l lt $lc lw 1
            print 'run $irun, spec $cur_spec: mean($ylabel)=',gprintf(\"%g\",m$lc),' +/- ',gprintf(\"%g\",stddev$lc),' (stddev)'" >> $tmppltfile
		cur_spec=`expr $cur_spec + 1`
		lc=`expr $lc + 1`
	    done
	    irun=`expr $irun + 1`
	done	    
	    
	echo "print '========================================='" >> $tmppltfile
    fi



##################### misc #########################################

    echo "press in plot window (GNUPLOT version >= 4.0 needed):"
#    echo "'a' to refresh"
    echo "'l' for logarithmic axis"
    echo "<return> in terminal for exit"

    echo "replot 0 notit lt 0" >> $tmppltfile

    if [ "$epsfile" != "" ]; then
	echo "set terminal postscript eps enhanced 'Times-Roman' 38 color
        set output '$epsfile'
        set size 1.5,1.5
        replot
        set output
        set terminal x11
        set xrange [$tmin:$tmax]
        set size 1.0,1.0" >> $tmppltfile
    fi
    
    echo "pause -1" >> $tmppltfile
    gnuplot $tmppltfile
    rm $tmppltfile
    rm $tmpdatfile
    rm -f $tmpfitfile
else
    echo "no neoclass file found"
fi

