#!/bin/sh
#run chain tool, requires timestamp path and parameters file
if [ $# -lt 1 ]
then
  echo "rc_chpt error: called without timestamp path" > rcerror.msg
  exit 1
fi
if [ "$2" == "-nochange" ]
then
  nochange=1
else
  nochange=0
fi
if [ "$2" == "-move" ]
then
  move=1
else
  move=0
fi
timestampcmd="${1}timestamp"

if [ ! -f parameters ]
then
  echo "rc_chpt error: no parameters file" > rcerror.msg
  exit 1
fi
diagdirline=`grep diagdir parameters | sed -e "s/ [ ]*/ /g" | grep "diagdir ="`
if [ `echo $diagdirline | wc -l` -ne 1 ] || [ `echo $nspecline | wc -l` -ne 1 ]
then
  echo "rc_chpt error: missing parameters: n_spec or diagdir" > rcerror.msg
  exit 1
fi
diagdir=`echo $diagdirline | tr "'" " " | tr '"' ' ' | tr "=" " " | sed -e "s/ [ ]*/ /g" | cut -d " " -f 2`
if [ ! "`echo $diagdir | awk '{ print substr($0,length($0),length($0)) }'`" == "/" ]
then
  diagdir="${diagdir}/"
fi
for datfile in `ls -t ${diagdir}*.dat`
do
  dummy=0
done
if [ ! -f "$datfile" ]
then
  echo "rc_chpt error: no data files" > rcerror.msg
  exit 1
fi
oldestdat=`$timestampcmd $datfile`

if [ -f "${diagdir}checkpoint" ]
then
  chptdat=`$timestampcmd ${diagdir}checkpoint`
  if [ -f "${diagdir}s_checkpoint" ]
  then
    schptdat=`$timestampcmd ${diagdir}s_checkpoint`
    if [ "$oldestdat" -ge "$schptdat" ] && [ "$oldestdat" -ge "$chptdat" ]
    then
      echo "rc_chpt error: checkpoint files older than data" > rcerror.msg
      exit 1
    fi
    if [ "$schptdat" -gt "$chptdat" ]
    then
      if [ $nochange -eq 0 ]
      then
        mv ${diagdir}s_checkpoint ${diagdir}checkpoint
      fi
    fi
  fi
else
  if [ -f "${diagdir}s_checkpoint" ]
  then
    schptdat=`$timestampcmd ${diagdir}s_checkpoint`
    if [ "$oldestdat" -ge "$schptdat" ]
    then
      echo "rc_chpt error: no checkpoint, no recent s_checkpoint" > rcerror.msg
      exit 1
    else
      if [ $nochange -eq 0 ]
      then
        mv ${diagdir}s_checkpoint ${diagdir}checkpoint
      fi
    fi
  else
    echo "rc_chpt error: no checkpoint files" > rcerror.msg
    exit 1
  fi
fi
if [ $nochange -eq 0 ]
then
  if [ $move -eq 0 ]
  then
    cp ${diagdir}checkpoint ${diagdir}checkpoint.dat
  else
    mv ${diagdir}checkpoint ${diagdir}checkpoint.dat
  fi
fi
exit 0
