#!/bin/sh
#run chain tool, requires existing parameter file
if [ ! -f parameters ]
then
  echo "rc_modpar error: no parameter file" > rcerror.msg
  exit 1
fi
if [ `grep read_checkpoint parameters | wc -l` -eq 0 ]
then
  if [ `grep diagdir parameters | wc -l` -eq 0 ]
  then
    echo "rc_modpar error: no diagdir in parameter file" > rcerror.msg
    exit 1
  fi
  awk "/diagdir.*/ { print;print \"\nread_checkpoint = .t.\";next }1" parameters > par.awktemp~
  mv par.awktemp~ parameters
else
  sed -e "s/read_checkpoint.*/read_checkpoint = .t./" parameters > par.sedtemp~
  mv par.sedtemp~ parameters
fi
exit 0
