#!/bin/sh
#run chain tool, forces run number assign in diagdir; argument: run number
if [ ! -f parameters ]
then
  echo "rc_runassign error: no parameters file" > rcerror.msg
  exit 1
fi
diagdirline=`grep diagdir parameters | sed -e "s/ [ ]*/ /g" | grep "diagdir ="`
if [ `echo $diagdirline | wc -l` -ne 1 ] || [ `echo $nspecline | wc -l` -ne 1 ]
then
  echo "rc_chpt error: missing parameters: n_spec or diagdir" > rcerror.msg
  exit 1
fi
diagdir=`echo $diagdirline | tr "'" " " | tr '"' ' ' | tr "=" " " | sed -e "s/ [ ]*/ /g" | cut -d " " -f 2`
if [ ! "`echo $diagdir | awk '{ print substr($0,length($0),length($0)) }'`" == "/" ]
then
  diagdir="${diagdir}/"
fi
currdir="`pwd`/"
cd ${diagdir}
for file_in in *.dat
do
  file_out=`echo $file_in | sed -e "s/\(.*\).dat/\1_$1/"`
  mv $file_in $file_out
done
touch *_*
cd ${currdir}
exit 0
