#!/bin/bash
#shifts range *_[number1] *_[number2] to new range starting at *_[number3]
#allows leading zeros in numbers, either for [number1]/[number2] range
#  or for range starting at [number3]
#usage: runshift [number1] [number2] [number3]
r4=`expr $3 + $2 - $1`
nruns=`expr $2 - $1 + 1`
ndigits_n1=${#1}
ndigits_n2=${#2}
ndigits_n3=${#3}
ndigits_n4=${#r4}

if [[ "${1:0:1}" -eq "0" || "${2:0:1}" -eq "0" ]]; then 
  in_has_0=1
  if [[ $ndigits_n1 -gt $ndigits_n2 ]]; then
    ndigits_in=$ndigits_n1
  else
    ndigits_in=$ndigits_n2
  fi
else
  in_has_0=0
fi
if [[ "${3:0:1}" -eq "0" || "${r4:0:1}" -eq "0" ]]; then
  out_has_0=1
  if [[ $ndigits_n3 -gt $ndigits_n4 ]]; then
    ndigits_out=$ndigits_n3
  else
    ndigits_out=$ndigits_n4
  fi
else
  out_has_0=0
fi

echo "shifting runs $1 - $2 to $3 - $r4"

i=0
while [ $i -lt $nruns ]
do
  inrun=`expr $1 + $i`
  outrun=`expr $3 + $i`
  if [[ $in_has_0 -eq 1 ]]; then
    inrun_ext=`printf "%0${ndigits_in}d" $inrun`
  else
    inrun_ext=$inrun
  fi
  if [[ $out_has_0 -eq 1 ]]; then
    outrun_ext=`printf "%0${ndigits_out}d" $outrun`
  else
    outrun_ext=$outrun
  fi

  echo "renaming $inrun_ext to $outrun_ext"

  if [[ `ls *_$inrun_ext *_${inrun_ext}.h5 2> /dev/null | wc -l` -eq 0 ]]; then
    echo "source does not exist"
    exit
  fi

  if [[ `ls *_$outrun_ext *_${outrun_ext}.h5 2> /dev/null | wc -l` -gt 0 ]]; then
    overwrite="y"
    echo "target already exists: overwrite (y/n)?"
    read overwrite
    if [ "$overwrite" != "y" ]
    then
      echo "exiting"
      exit
    fi
  fi

  if [[ `ls *_$inrun_ext 2> /dev/null | wc -l` -gt 0 ]]; then
    for file_in in *_$inrun_ext
    do
      file_out=`echo $file_in | sed -e "s/\(.*\)_${inrun_ext}/\1_${outrun_ext}/"`
      mv $file_in $file_out
    done
  fi

  if [[ `ls *_${inrun_ext}.h5 2> /dev/null | wc -l` -gt 0 ]]; then
    for file_in in *_${inrun_ext}.h5
    do
      file_out=`echo $file_in | sed -e "s/\(.*\)_${inrun_ext}.h5/\1_${outrun_ext}.h5/"`
      mv $file_in $file_out
    done
  fi

  i=`expr $i + 1`
done
