#define SIZE_OF_INTEGER 4
#define SIZE_OF_INTEGER_MB (SIZE_OF_INTEGER/1048576.)
#define SIZE_OF_LOGICAL 4
#define SIZE_OF_LOGICAL_MB (SIZE_OF_LOGICAL/1048576.)
#ifdef DOUBLE_PREC
#define SIZE_OF_REAL 8
#else
#define SIZE_OF_REAL 4
#endif
#define SIZE_OF_REAL_MB (SIZE_OF_REAL/1048576.)
#define SIZE_OF_COMPLEX (2*SIZE_OF_REAL)
#define SIZE_OF_COMPLEX_MB (SIZE_OF_COMPLEX/1048576.)
#define SIZE_OF_CHAR 1
#define SIZE_OF_CHAR_MB (SIZE_OF_CHAR/1048576.)
#define SIZE_OF_POINTER 4
#define SIZE_OF_POINTER_MB (SIZE_OF_POINTER/1048576.)
#define FILENAME_MAX 200
